# Generated by Django 5.0.5 on 2024-05-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hadith_post',
            name='Darajet_alhadith',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
