# Generated by Django 5.0.5 on 2024-05-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_hadith_post_darajet_alhadith'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadith_post',
            name='Darajet_alhadith',
            field=models.CharField(choices=[('Option 1', 'Option 1 Label'), ('Option 2', 'Option 2 Label'), ('Option 3', 'Option 3 Label')], max_length=100),
        ),
    ]
