# Generated by Django 5.0.5 on 2024-05-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_hadith_post_darajet_alhadith'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadith_post',
            name='Darajet_alhadith',
            field=models.CharField(choices=[('صحيح متفق عليه', 'صحيح متفق عليه'), ('صحيح أخرجه بخاري', 'صحيح أخرجه بخاري'), ('أخرجه أصحاب السُنَن', 'أخرجه أصحاب السُنَن'), ('إسناده صحيح', 'إسناده صحيح'), ('صحيح بشواهد', 'صحيح بشواهد'), ('إسناده حسن', 'إسناده حسن'), ('حسن مع إمعاض', 'حسن مع إمعاض'), ('ضعيف منجبر', 'ضعيف منجبر'), ('موقوف', 'موقوف'), ('معلول', 'معلول'), ('لا وجود له', 'لا وجود له'), ('مكذوب', 'مكذوب'), ('لا أصل له', 'لا أصل له'), ('لا يصح', 'لا يصح'), ('باطل', 'باطل'), ('مُنكر', 'مُنكر'), ('ضعيف جداً', 'ضعيف جداً'), ('ضعيف', 'ضعيف'), ('شاذ', 'شاذ')], max_length=100),
        ),
    ]
